#!/usr/bin/env ruby

#
#  spawn  --  Example that produces two tables for dirs and files
#

require "rbfind"
require "rbfind/humansiz"
require "rbfind/table"

t = RbFind::Table.new "Mode", "Size>", "Age>", "Path", "Dest"
s = t.spawn
RbFind.run max_depth: 1 do
  (dir? ? s : t).add stype+modes, size, age.to_i.t, path, readlink, +age
end

s.sort_by! 3
t.sort_by! 5, 3

s.output
puts
t.output

